### ISSUE TITLE
add support file

### ISSUE THREAD

**Issue by juanpablocs** [DeviousM/razzle-plugin-svgr#1]
Please add support with import file or component

example

```js
import { ReactComponent as Logo } from './logo.svg';
// usage <Logo />

//or
import logo from './logo.svg';
// usage <img src={logo} />

```

**Comment by DeviousM** [comment]
Hi, SVGR is made to solve the issue of importing SVG files to React apps. It converts them to React components, but doesn't allow for URL imports. If you want to achieve that, you probably will want to use the webpack's standard file-loader.

**Comment by juanpablocs** [comment]
I would like to use both as in webpack.

When I use your plugin, the svg files can no longer be imported as a file.

In a complex react application I cannot change all the svg to components, so I would like to have both options with its plugin.

**Comment by DeviousM** [comment]
So you'd want it to work the way create-react-app makes it work?

**Comment by juanpablocs** [comment]
thanks, it's done here.

https://github.com/finmavis/razzle-plugin-svg-react-component
