### ISSUE TITLE
image require don't work

### ISSUE THREAD

**Issue by mskarimi** [DeviousM/razzle-plugin-svgr#2]
when use this pulgin don't load local image 
what is solution???

**Comment by DeviousM** [comment]
Could you share more information? Like the path that you're trying to load or more details on the config of your project.

**Comment by mskarimi** [comment]
<img src={require('imagePath')} alt={'description'} />
I try show local image with img tag.
The img tag did not work after installing the plugin

**Comment by DeviousM** [comment]
Sorry mate, that's not how it works. Check out documentation for svgr first: https://github.com/gregberge/svgr
